# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: fenics-smart
author: Justin Laughlin
copyright: "2022"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  timeout: 3000

# Information about where the book exists on the web
repository:
  url: https://github.com/RangamaniLabUCSD/smart # Online location of your book
  branch: development


html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:

  config:
    html_last_updated_fmt: "%b %d, %Y"
    autoapi_dirs: ['smart']
    # Ref: https://github.com/executablebooks/sphinx-external-toc/issues/36
    suppress_warnings: ["etoc.toctree"]

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autosummary'
  - 'autoapi.extension'
