name: Run examples

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - development
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - development

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
jobs:
  run-examples:
    strategy:
      fail-fast: false
      matrix:
        example: [1, 2, 3, 4, 5, 6]
    runs-on: ubuntu-22.04
    # Runs against FEniCS main branch built the 16-01-2023
    container: ghcr.io/scientificcomputing/fenics-gmsh:2023-04-21
    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3

      - name: "Install code"
        run: python3 -m pip install ".[dev,examples]" jupytext

      - name: Run example ${{ matrix.example }}
        run: |
          cd examples/example${{ matrix.example }}/
          jupytext example${{ matrix.example }}.ipynb --to py
          python3 example${{ matrix.example }}.py

      - name: Run MPI example
        run: mpirun -n 2 python3 examples/example3/example3_multimeshMPI.py
